grow_version: ">=0.7.4"
home: /content/amp-dev/index.html

localization:
  root_path: /{locale}/
  default_locale: en

sitemap:
  enabled: yes
  path: '/sitemap_grow.xml'
  template: '/layouts/sitemap.xml'

markdown:
  extensions:
  - kind: sourcecode
    classes: True
    class_name: ap-m-code-snippet
  - kind: markdown.extensions.codehilite
    classes: True
    class_name: ap-m-code-snippet

ext:
- extensions.inline_text_assets.InlineTextAssetsExtension:
    bundles:
        - name: 'styles'
          method: 'addCssFile'
        - name: 'icons'
          method: 'useIcon'
- extensions.amp_dev.AmpDevExtension
- extensions.amp_example_preview.AmpExamplePreviewExtension
- extensions.amp_dependency_injector.AmpDependencyInjectorExtension
- extensions.url_beautifier.UrlBeautifierExtension
- extensions.jinja2_optimized_codehilite.Jinja2OptimizedCodehiliteExtension
